export interface Node {
  id: string;
  type: "organization" | "product" | "software" | "vulnerability";
  name: string;
  risk_score: number;
  exposure_level?: string;
  last_updated?: string;
  description?: string;
  version?: string;
  vendor?: string;
  severity?: "critical" | "high" | "medium" | "low";
  affected_systems?: number;
}

export interface Edge {
  source: string;
  target: string;
  relation: "uses" | "depends_on" | "affected_by" | "supplies_to";
  confidence?: number;
  last_verified?: string;
  impact_score?: number;
}

export interface GraphData {
  nodes: Node[];
  edges: Edge[];
}

export const graphData: GraphData = {
  nodes: [
    // Organizations
    {
      id: "org_mtl",
      type: "organization",
      name: "City of Montreal",
      risk_score: 45,
      description: "Municipal government entity",
      last_updated: "2025-10-20",
      affected_systems: 12,
    },
    {
      id: "org_micrologic",
      type: "organization",
      name: "Micrologic",
      risk_score: 72,
      description: "IT services provider",
      last_updated: "2025-10-23",
      affected_systems: 8,
      severity: "high",
    },
    {
      id: "org_techcorp",
      type: "organization",
      name: "TechCorp Solutions",
      risk_score: 38,
      description: "Technology consulting firm",
      last_updated: "2025-10-22",
      affected_systems: 5,
    },
    {
      id: "org_dataflow",
      type: "organization",
      name: "DataFlow Inc",
      risk_score: 55,
      description: "Data analytics platform",
      last_updated: "2025-10-21",
      affected_systems: 6,
    },
    {
      id: "org_cloudserve",
      type: "organization",
      name: "CloudServe",
      risk_score: 68,
      description: "Cloud infrastructure provider",
      last_updated: "2025-10-24",
      affected_systems: 9,
      severity: "high",
    },

    // Products
    {
      id: "product_veeam",
      type: "product",
      name: "Veeam Cloud Connect",
      risk_score: 65,
      version: "12.1.2",
      vendor: "Veeam Software",
      description: "Backup and disaster recovery solution",
      last_updated: "2025-10-18",
      affected_systems: 4,
    },
    {
      id: "product_openshift",
      type: "product",
      name: "OpenShift Platform",
      risk_score: 42,
      version: "4.14",
      vendor: "Red Hat",
      description: "Kubernetes container platform",
      last_updated: "2025-10-19",
    },
    {
      id: "product_jenkins",
      type: "product",
      name: "Jenkins CI/CD",
      risk_score: 58,
      version: "2.426.1",
      vendor: "Jenkins Project",
      description: "Automation server",
      last_updated: "2025-10-17",
      affected_systems: 3,
    },
    {
      id: "product_splunk",
      type: "product",
      name: "Splunk Enterprise",
      risk_score: 35,
      version: "9.1.2",
      vendor: "Splunk",
      description: "Log analysis platform",
      last_updated: "2025-10-20",
    },
    {
      id: "product_docker",
      type: "product",
      name: "Docker Enterprise",
      risk_score: 48,
      version: "24.0.6",
      vendor: "Docker Inc",
      description: "Container platform",
      last_updated: "2025-10-16",
    },
    {
      id: "product_k8s",
      type: "product",
      name: "Kubernetes",
      risk_score: 52,
      version: "1.28.3",
      vendor: "CNCF",
      description: "Container orchestration",
      last_updated: "2025-10-21",
      affected_systems: 7,
    },
    {
      id: "product_postgres",
      type: "product",
      name: "PostgreSQL",
      risk_score: 30,
      version: "16.1",
      vendor: "PostgreSQL Global Development Group",
      description: "Relational database",
      last_updated: "2025-10-15",
    },

    // Software Components
    {
      id: "software_log4j",
      type: "software",
      name: "Log4j",
      risk_score: 85,
      version: "2.17.0",
      vendor: "Apache",
      description: "Java logging framework",
      last_updated: "2025-10-12",
      affected_systems: 11,
      severity: "critical",
    },
    {
      id: "software_nginx",
      type: "software",
      name: "nginx",
      risk_score: 40,
      version: "1.25.3",
      vendor: "F5",
      description: "Web server",
      last_updated: "2025-10-14",
    },
    {
      id: "software_openssl",
      type: "software",
      name: "OpenSSL",
      risk_score: 62,
      version: "3.0.12",
      vendor: "OpenSSL Project",
      description: "Cryptography library",
      last_updated: "2025-10-13",
      affected_systems: 8,
      severity: "high",
    },
    {
      id: "software_redis",
      type: "software",
      name: "Redis",
      risk_score: 45,
      version: "7.2.3",
      vendor: "Redis Ltd",
      description: "In-memory data store",
      last_updated: "2025-10-11",
    },
    {
      id: "software_spring",
      type: "software",
      name: "Spring Framework",
      risk_score: 55,
      version: "6.1.0",
      vendor: "VMware",
      description: "Java application framework",
      last_updated: "2025-10-10",
      affected_systems: 5,
    },
    {
      id: "software_jackson",
      type: "software",
      name: "Jackson",
      risk_score: 48,
      version: "2.16.0",
      vendor: "FasterXML",
      description: "JSON processor",
      last_updated: "2025-10-09",
    },
    {
      id: "software_tomcat",
      type: "software",
      name: "Apache Tomcat",
      risk_score: 50,
      version: "10.1.16",
      vendor: "Apache",
      description: "Servlet container",
      last_updated: "2025-10-08",
      affected_systems: 4,
    },

    // Vulnerabilities
    {
      id: "vuln_cve2021_44228",
      type: "vulnerability",
      name: "CVE-2021-44228 (Log4Shell)",
      risk_score: 95,
      description: "Remote code execution via JNDI lookup",
      severity: "critical",
      last_updated: "2021-12-10",
      affected_systems: 11,
    },
    {
      id: "vuln_cve2024_1234",
      type: "vulnerability",
      name: "CVE-2024-1234",
      risk_score: 78,
      description: "Memory corruption vulnerability",
      severity: "high",
      last_updated: "2024-03-15",
      affected_systems: 8,
    },
    {
      id: "vuln_cve2024_5678",
      type: "vulnerability",
      name: "CVE-2024-5678",
      risk_score: 82,
      description: "Path traversal vulnerability",
      severity: "high",
      last_updated: "2024-06-20",
      affected_systems: 7,
    },
    {
      id: "vuln_cve2025_9999",
      type: "vulnerability",
      name: "CVE-2025-9999",
      risk_score: 88,
      description: "Authentication bypass",
      severity: "critical",
      last_updated: "2025-01-08",
      affected_systems: 5,
    },
    {
      id: "vuln_cve2024_3333",
      type: "vulnerability",
      name: "CVE-2024-3333",
      risk_score: 70,
      description: "Privilege escalation",
      severity: "high",
      last_updated: "2024-09-12",
      affected_systems: 4,
    },
  ],
  edges: [
    {
      source: "org_mtl",
      target: "org_micrologic",
      relation: "supplies_to",
      confidence: 0.95,
      impact_score: 85,
    },
    {
      source: "org_mtl",
      target: "org_techcorp",
      relation: "supplies_to",
      confidence: 0.88,
      impact_score: 72,
    },
    {
      source: "org_micrologic",
      target: "org_cloudserve",
      relation: "supplies_to",
      confidence: 0.82,
      impact_score: 68,
    },
    {
      source: "org_techcorp",
      target: "org_dataflow",
      relation: "supplies_to",
      confidence: 0.9,
      impact_score: 75,
    },

    {
      source: "org_micrologic",
      target: "product_veeam",
      relation: "uses",
      confidence: 0.92,
      impact_score: 78,
    },
    {
      source: "org_micrologic",
      target: "product_jenkins",
      relation: "uses",
      confidence: 0.87,
      impact_score: 65,
    },
    {
      source: "org_techcorp",
      target: "product_openshift",
      relation: "uses",
      confidence: 0.9,
      impact_score: 70,
    },
    {
      source: "org_techcorp",
      target: "product_docker",
      relation: "uses",
      confidence: 0.85,
      impact_score: 62,
    },
    {
      source: "org_dataflow",
      target: "product_splunk",
      relation: "uses",
      confidence: 0.88,
      impact_score: 58,
    },
    {
      source: "org_cloudserve",
      target: "product_k8s",
      relation: "uses",
      confidence: 0.93,
      impact_score: 82,
    },
    {
      source: "org_cloudserve",
      target: "product_postgres",
      relation: "uses",
      confidence: 0.89,
      impact_score: 55,
    },

    {
      source: "product_veeam",
      target: "software_log4j",
      relation: "depends_on",
      confidence: 0.85,
      impact_score: 90,
    },
    {
      source: "product_veeam",
      target: "software_openssl",
      relation: "depends_on",
      confidence: 0.9,
      impact_score: 75,
    },
    {
      source: "product_jenkins",
      target: "software_log4j",
      relation: "depends_on",
      confidence: 0.88,
      impact_score: 85,
    },
    {
      source: "product_openshift",
      target: "software_nginx",
      relation: "depends_on",
      confidence: 0.92,
      impact_score: 68,
    },
    {
      source: "product_openshift",
      target: "software_redis",
      relation: "depends_on",
      confidence: 0.87,
      impact_score: 60,
    },
    {
      source: "product_docker",
      target: "software_openssl",
      relation: "depends_on",
      confidence: 0.91,
      impact_score: 72,
    },
    {
      source: "product_splunk",
      target: "software_spring",
      relation: "depends_on",
      confidence: 0.86,
      impact_score: 65,
    },
    {
      source: "product_k8s",
      target: "software_nginx",
      relation: "depends_on",
      confidence: 0.89,
      impact_score: 70,
    },
    {
      source: "product_postgres",
      target: "software_openssl",
      relation: "depends_on",
      confidence: 0.93,
      impact_score: 58,
    },
    {
      source: "product_jenkins",
      target: "software_tomcat",
      relation: "depends_on",
      confidence: 0.84,
      impact_score: 62,
    },

    {
      source: "software_log4j",
      target: "vuln_cve2021_44228",
      relation: "affected_by",
      confidence: 1.0,
      impact_score: 98,
    },
    {
      source: "software_openssl",
      target: "vuln_cve2024_1234",
      relation: "affected_by",
      confidence: 0.95,
      impact_score: 82,
    },
    {
      source: "software_nginx",
      target: "vuln_cve2024_5678",
      relation: "affected_by",
      confidence: 0.92,
      impact_score: 78,
    },
    {
      source: "software_spring",
      target: "vuln_cve2025_9999",
      relation: "affected_by",
      confidence: 0.97,
      impact_score: 88,
    },
    {
      source: "software_tomcat",
      target: "vuln_cve2024_3333",
      relation: "affected_by",
      confidence: 0.89,
      impact_score: 72,
    },
  ],
};
